kerala_food = {
    "breakfast": {
      "base_items": {
        "core_items": [
          { "name": "Idli", "calories": 45, "unit": "piece" },
          { "name": "Dosa", "calories": 90, "unit": "piece" },
          { "name": "Masala Dosa", "calories": 275, "unit": "piece" },
          { "name": "Ghee Roast Dosa", "calories": 320, "unit": "piece" },
          { "name": "Rava Dosa", "calories": 200, "unit": "piece" },
          { "name": "Wheat Dosa", "calories": 100, "unit": "piece" },
          { "name": "Ragi Dosa", "calories": 120, "unit": "piece" },
          { "name": "Neer Dosa", "calories": 80, "unit": "piece" },
          { "name": "Onion Uthappam", "calories": 180, "unit": "piece" },
          { "name": "Plain Uthappam", "calories": 150, "unit": "piece" },
          { "name": "Appam", "calories": 95, "unit": "piece" },
          { "name": "Idiyappam", "calories": 65, "unit": "piece" },
          { "name": "Puttu", "calories": 275, "unit": "piece" },
          { "name": "Pathiri", "calories": 120, "unit": "piece" },
          { "name": "Parotta", "calories": 275, "unit": "piece" },
          { "name": "Poori", "calories": 150, "unit": "piece" },
          { "name": "Chapati", "calories": 110, "unit": "piece" },
          { "name": "Roti", "calories": 110, "unit": "piece" },
          { "name": "Bread", "calories": 70, "unit": "slice" },
          { "name": "Pav", "calories": 80, "unit": "piece" }
        ],
        "complete_dishes": [
          { "name": "Upma", "calories": 225, "unit": "cup" },
          { "name": "Semiya Upma", "calories": 250, "unit": "cup" },
          { "name": "Aval Upma", "calories": 200, "unit": "cup" },
          { "name": "Pongal", "calories": 220, "unit": "cup" },
          { "name": "Ela Ada", "calories": 150, "unit": "piece" },
          { "name": "Kappa", "calories": 180, "unit": "cup" },
          { "name": "Banana", "calories": 105, "unit": "medium" }
        ]
      },
      "veg_items": {
        "gravy": [
          { "name": "Vegetable Stew", "calories": 150, "unit": "cup" },
          { "name": "Kadala Curry", "calories": 220, "unit": "cup" },
          { "name": "Sambar", "calories": 135, "unit": "cup" },
          { "name": "Coconut Chutney", "calories": 45, "unit": "tbsp" },
          { "name": "Tomato Chutney", "calories": 30, "unit": "tbsp" },
          { "name": "Mint Chutney", "calories": 25, "unit": "tbsp" },
          { "name": "Potato Masala", "calories": 200, "unit": "cup" },
          { "name": "Chana Curry", "calories": 210, "unit": "cup" },
          { "name": "Coconut Milk", "calories": 50, "unit": "tbsp" },
          { "name": "Mulaku Chammanthi", "calories": 30, "unit": "tbsp" },
          { "name": "Kappa Puzhukku", "calories": 180, "unit": "cup" },
          { "name": "Thari Kanji", "calories": 120, "unit": "cup" },
          { "name": "Vendakka Stew", "calories": 140, "unit": "cup" },
          { "name": "Kumbalanga Stew", "calories": 130, "unit": "cup" },
          { "name": "Kappa Vevichathu", "calories": 160, "unit": "cup" },
          { "name": "Red Chilli Chutney", "calories": 35, "unit": "tbsp" },
          { "name": "Pazham Kanji", "calories": 110, "unit": "cup" },
          { "name": "Coconut Milk Kanji", "calories": 140, "unit": "cup" },
          { "name": "Uluva Kanji", "calories": 125, "unit": "cup" },
          { "name": "Vegetable Kurma", "calories": 165, "unit": "cup" },
          { "name": "Avial", "calories": 170, "unit": "cup" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Fish Stew", "calories": 240, "unit": "cup" },
          { "name": "Chicken Curry", "calories": 275, "unit": "cup" },
          { "name": "Egg Roast", "calories": 200, "unit": "cup" },
          { "name": "Egg Dosa", "calories": 180, "unit": "piece" },
          { "name": "Egg Appam", "calories": 150, "unit": "piece" },
          { "name": "Mutta Roast", "calories": 210, "unit": "cup" },
          { "name": "Mutta Curry", "calories": 190, "unit": "cup" },
          { "name": "Fish Molee", "calories": 250, "unit": "cup" },
          { "name": "Chemmeen Roast", "calories": 280, "unit": "cup" },
          { "name": "Prawns Stew", "calories": 260, "unit": "cup" },
          { "name": "Chicken Kurma", "calories": 290, "unit": "cup" },
          { "name": "Egg Masala", "calories": 195, "unit": "cup" }
        ]
      }
    },
    "lunch": {
      "base_items": {
        "core_items": [
          { "name": "Rice", "calories": 180, "unit": "cup" },
          { "name": "Brown Rice", "calories": 215, "unit": "cup" },
          { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
          { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
          { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
          { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
          { "name": "Kaima Rice", "calories": 185, "unit": "cup" },
          { "name": "Neychoru", "calories": 280, "unit": "cup" },
          { "name": "Tomato Rice", "calories": 220, "unit": "cup" },
          { "name": "Lemon Rice", "calories": 240, "unit": "cup" },
          { "name": "Curd Rice", "calories": 200, "unit": "cup" },
          { "name": "Tamarind Rice", "calories": 250, "unit": "cup" },
          { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
          { "name": "Chapati", "calories": 110, "unit": "piece" },
          { "name": "Roti", "calories": 110, "unit": "piece" },
          { "name": "Parotta", "calories": 275, "unit": "piece" },
          { "name": "Pathiri", "calories": 120, "unit": "piece" }
        ],
        "complete_dishes": [
          { "name": "Kerala Sadya", "calories": 400, "unit": "plate" },
          { "name": "Fried Rice", "calories": 280, "unit": "cup" },
          { "name": "Pulao", "calories": 250, "unit": "cup" },
          { "name": "Biryani", "calories": 325, "unit": "cup" },
          { "name": "Vegetable Biryani", "calories": 255, "unit": "cup" },
          { "name": "Thalassery Veg Biryani", "calories": 260, "unit": "cup" }
        ]
      },
      "veg_items": {
        "gravy": [
          { "name": "Sambar", "calories": 135, "unit": "cup" },
          { "name": "Rasam", "calories": 70, "unit": "cup" },
          { "name": "Moru Curry", "calories": 120, "unit": "cup" },
          { "name": "Avial", "calories": 170, "unit": "cup" },
          { "name": "Olan", "calories": 100, "unit": "cup" },
          { "name": "Kalan", "calories": 140, "unit": "cup" },
          { "name": "Erissery", "calories": 150, "unit": "cup" },
          { "name": "Pachadi", "calories": 130, "unit": "cup" },
          { "name": "Inji Curry", "calories": 80, "unit": "cup" },
          { "name": "Theeyal", "calories": 160, "unit": "cup" },
          { "name": "Koottu Curry", "calories": 145, "unit": "cup" },
          { "name": "Pulissery", "calories": 125, "unit": "cup" },
          { "name": "Parippu Curry", "calories": 165, "unit": "cup" },
          { "name": "Coconut Chammanthi", "calories": 40, "unit": "tbsp" },
          { "name": "Bitter Gourd Theeyal", "calories": 155, "unit": "cup" },
          { "name": "Ash Gourd Pulissery", "calories": 120, "unit": "cup" },
          { "name": "Beetroot Pachadi", "calories": 135, "unit": "cup" },
          { "name": "Okra Curry", "calories": 140, "unit": "cup" },
          { "name": "Tomato Rasam", "calories": 75, "unit": "cup" },
          { "name": "Ulli Theeyal", "calories": 165, "unit": "cup" },
          { "name": "Drumstick Curry", "calories": 130, "unit": "cup" },
          { "name": "Jackfruit Erissery", "calories": 160, "unit": "cup" },
          { "name": "Pumpkin Curry", "calories": 115, "unit": "cup" },
          { "name": "Mango Pulissery", "calories": 140, "unit": "cup" },
          { "name": "Vegetable Roast", "calories": 160, "unit": "cup" },
          { "name": "Vegetable Ishtu", "calories": 155, "unit": "cup" },
          { "name": "Raw Mango Curry", "calories": 145, "unit": "cup" },
          { "name": "Dal Fry", "calories": 170, "unit": "cup" },
          { "name": "Vegetable Kurma", "calories": 165, "unit": "cup" },
          { "name": "Vegetable Stew", "calories": 150, "unit": "cup" },
          { "name": "Kadala Curry", "calories": 220, "unit": "cup" }
        ],
        "dry": [
          { "name": "Thoran", "calories": 110, "unit": "cup" },
          { "name": "Long Beans Thoran", "calories": 105, "unit": "cup" },
          { "name": "Cabbage Thoran", "calories": 100, "unit": "cup" },
          { "name": "Chena Mezhukkupuratti", "calories": 180, "unit": "cup" },
          { "name": "Kovakka Thoran", "calories": 110, "unit": "cup" },
          { "name": "Payar Mezhukkupuratti", "calories": 125, "unit": "cup" },
          { "name": "Koorka Fry", "calories": 150, "unit": "cup" },
          { "name": "Kaya Mezhukkupuratti", "calories": 175, "unit": "cup" },
          { "name": "Veg Manchurian", "calories": 200, "unit": "cup" },
          { "name": "Banana Chips", "calories": 150, "unit": "serving" },
          { "name": "Sharkkara Upperi", "calories": 180, "unit": "serving" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Kerala Fish Curry", "calories": 260, "unit": "cup" },
          { "name": "Meen Vevichathu", "calories": 270, "unit": "cup" },
          { "name": "Sardine Curry", "calories": 250, "unit": "cup" },
          { "name": "Ayala Curry", "calories": 255, "unit": "cup" },
          { "name": "Prawns Curry", "calories": 270, "unit": "cup" },
          { "name": "Chicken Curry", "calories": 275, "unit": "cup" },
          { "name": "Nadan Kozhi Curry", "calories": 285, "unit": "cup" },
          { "name": "Chicken Chettinad", "calories": 300, "unit": "cup" },
          { "name": "Mutton Curry", "calories": 320, "unit": "cup" },
          { "name": "Mutton Stew", "calories": 290, "unit": "cup" },
          { "name": "Duck Curry", "calories": 300, "unit": "cup" },
          { "name": "Egg Curry", "calories": 200, "unit": "cup" },
          { "name": "Fish Molee", "calories": 250, "unit": "cup" }
        ],
        "dry": [
          { "name": "Meen Pollichathu", "calories": 280, "unit": "cup" },
          { "name": "Fish Fry", "calories": 175, "unit": "piece" },
          { "name": "King Fish Fry", "calories": 200, "unit": "piece" },
          { "name": "Crab Roast", "calories": 290, "unit": "cup" },
          { "name": "Prawns Roast", "calories": 285, "unit": "cup" },
          { "name": "Prawns Masala", "calories": 275, "unit": "cup" },
          { "name": "Kanava Roast", "calories": 280, "unit": "cup" },
          { "name": "Kanava Thoran", "calories": 200, "unit": "cup" },
          { "name": "Mussel Fry", "calories": 190, "unit": "cup" },
          { "name": "Chicken Roast", "calories": 325, "unit": "cup" },
          { "name": "Chicken Varattiyathu", "calories": 310, "unit": "cup" },
          { "name": "Pepper Chicken Roast", "calories": 320, "unit": "cup" },
          { "name": "Chicken Fry", "calories": 325, "unit": "cup" },
          { "name": "Mutton Varattiyathu", "calories": 330, "unit": "cup" },
          { "name": "Beef Ularthiyathu", "calories": 340, "unit": "cup" },
          { "name": "Beef Roast", "calories": 350, "unit": "cup" },
          { "name": "Beef Fry", "calories": 360, "unit": "cup" },
          { "name": "Duck Roast", "calories": 310, "unit": "cup" },
          { "name": "Egg Roast", "calories": 210, "unit": "cup" },
          { "name": "Mutta Thoran", "calories": 180, "unit": "cup" },
          { "name": "Thalassery Chicken Biryani", "calories": 350, "unit": "cup" },
          { "name": "Malabar Mutton Biryani", "calories": 380, "unit": "cup" },
          { "name": "Fish Biryani", "calories": 340, "unit": "cup" },
          { "name": "Prawns Biryani", "calories": 360, "unit": "cup" },
          { "name": "Egg Biryani", "calories": 320, "unit": "cup" },
          { "name": "Chicken Manchurian", "calories": 280, "unit": "cup" },
          { "name": "Mutton Fry", "calories": 335, "unit": "cup" }
        ]
      }
    },
    "dinner": {
      "base_items": {
        "core_items": [
          { "name": "Rice", "calories": 180, "unit": "cup" },
          { "name": "Brown Rice", "calories": 215, "unit": "cup" },
          { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
          { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
          { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
          { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
          { "name": "Neychoru", "calories": 280, "unit": "cup" },
          { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
          { "name": "Chapati", "calories": 110, "unit": "piece" },
          { "name": "Roti", "calories": 110, "unit": "piece" },
          { "name": "Parotta", "calories": 275, "unit": "piece" },
          { "name": "Kerala Parotta", "calories": 280, "unit": "piece" },
          { "name": "Pathiri", "calories": 120, "unit": "piece" }
        ],
        "complete_dishes": [
          { "name": "Fried Rice", "calories": 280, "unit": "cup" },
          { "name": "Pulao", "calories": 250, "unit": "cup" },
          { "name": "Biryani", "calories": 325, "unit": "cup" },
          { "name": "Kothu Parotta", "calories": 350, "unit": "cup" },
          { "name": "Vegetable Fried Rice", "calories": 280, "unit": "cup" },
          { "name": "Corn & Peas Pulao", "calories": 260, "unit": "cup" },
          { "name": "Ela Ada (Light dinner)", "calories": 150, "unit": "piece" }
        ]
      },
      "veg_items": {
        "gravy": [
          { "name": "Vegetable Kurma", "calories": 165, "unit": "cup" },
          { "name": "Vegetable Stew", "calories": 150, "unit": "cup" },
          { "name": "Vegetable Ishtu", "calories": 155, "unit": "cup" },
          { "name": "Chakka Puzhukku", "calories": 140, "unit": "cup" },
          { "name": "Kadala Curry", "calories": 220, "unit": "cup" },
          { "name": "Tomato Kurma", "calories": 160, "unit": "cup" },
          { "name": "Vegetable Masala", "calories": 170, "unit": "cup" },
          { "name": "Potato Curry", "calories": 200, "unit": "cup" },
          { "name": "Dal Fry", "calories": 170, "unit": "cup" },
          { "name": "Paneer Masala", "calories": 280, "unit": "cup" },
          { "name": "Pumpkin Curry", "calories": 115, "unit": "cup" },
          { "name": "Beetroot Curry", "calories": 130, "unit": "cup" },
          { "name": "Cucumber Pachadi", "calories": 120, "unit": "cup" },
          { "name": "Mango Curry", "calories": 145, "unit": "cup" },
          { "name": "Mushroom Curry", "calories": 150, "unit": "cup" },
          { "name": "Paneer Butter Masala", "calories": 320, "unit": "cup" },
          { "name": "Baby Corn Kurma", "calories": 155, "unit": "cup" },
          { "name": "Soya Chunk Curry", "calories": 190, "unit": "cup" },
          { "name": "Pineapple Pulissery", "calories": 140, "unit": "cup" },
          { "name": "Chena Theeyal", "calories": 165, "unit": "cup" },
          { "name": "Nenthra Pazham Curry", "calories": 150, "unit": "cup" },
          { "name": "Vendakka Masala", "calories": 145, "unit": "cup" },
          { "name": "Chammanthi", "calories": 40, "unit": "tbsp" },
          { "name": "Chutney", "calories": 35, "unit": "tbsp" },
          { "name": "Mint Chutney", "calories": 25, "unit": "tbsp" }
        ],
        "dry": [
          { "name": "Vegetable Cutlet", "calories": 150, "unit": "piece" },
          { "name": "Thoran", "calories": 110, "unit": "cup" },
          { "name": "Bitter Gourd Fry", "calories": 140, "unit": "cup" },
          { "name": "Cabbage Thoran", "calories": 100, "unit": "cup" },
          { "name": "Beans Mezhukkupuratti", "calories": 120, "unit": "cup" },
          { "name": "Drumstick Leaves Thoran", "calories": 105, "unit": "cup" },
          { "name": "Carrot Thoran", "calories": 95, "unit": "cup" },
          { "name": "Raw Banana Fry", "calories": 160, "unit": "cup" },
          { "name": "Veg Roll", "calories": 200, "unit": "piece" },
          { "name": "Mushroom Thoran", "calories": 115, "unit": "cup" },
          { "name": "Soya Thoran", "calories": 125, "unit": "cup" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Chicken Curry", "calories": 275, "unit": "cup" },\
          { "name": "Beef Curry", "calories": 330, "unit": "cup" },
          { "name": "Beef Stew", "calories": 320, "unit": "cup" },
          { "name": "Mutton Curry", "calories": 320, "unit": "cup" },
          { "name": "Mutton Stew", "calories": 290, "unit": "cup" },
          { "name": "Fish Molee", "calories": 250, "unit": "cup" },
          { "name": "Meen Vevichathu", "calories": 270, "unit": "cup" },
          { "name": "Fish Molly", "calories": 255, "unit": "cup" },
          { "name": "Kanava Curry", "calories": 275, "unit": "cup" },
          { "name": "Egg Curry", "calories": 200, "unit": "cup" },
          { "name": "Egg Kurma", "calories": 205, "unit": "cup" },
          { "name": "Duck Curry", "calories": 300, "unit": "cup" }
        ],
        "dry": [
          { "name": "Chicken Roast", "calories": 325, "unit": "cup" },
          { "name": "Chicken Fried Rice", "calories": 320, "unit": "cup" },
          { "name": "Chicken 65", "calories": 300, "unit": "cup" },
          { "name": "Chicken Chukka", "calories": 310, "unit": "cup" },
          { "name": "Chicken Kothu", "calories": 350, "unit": "cup" },
          { "name": "Beef Fry", "calories": 360, "unit": "cup" },
          { "name": "Beef Roast", "calories": 350, "unit": "cup" },
          { "name": "Beef Kothu", "calories": 380, "unit": "cup" },
          { "name": "Mutton Fry", "calories": 335, "unit": "cup" },
          { "name": "Mutton Ularthiyathu", "calories": 330, "unit": "cup" },
          { "name": "Mutton Kothu", "calories": 370, "unit": "cup" },
          { "name": "Fish Fry", "calories": 175, "unit": "piece" },
          { "name": "Squid Roast", "calories": 285, "unit": "cup" },
          { "name": "Mussel Fry", "calories": 190, "unit": "cup" },
          { "name": "Egg Roast", "calories": 210, "unit": "cup" },
          { "name": "Egg Masala", "calories": 195, "unit": "cup" },
          { "name": "Egg Fried Rice", "calories": 300, "unit": "cup" },
          { "name": "Egg Kothu", "calories": 280, "unit": "cup" },
          { "name": "Prawns Fried Rice", "calories": 340, "unit": "cup" },
          { "name": "Prawns Masala Wrap", "calories": 290, "unit": "piece" },
          { "name": "Chicken Wrap", "calories": 310, "unit": "piece" },
          { "name": "Fish Wrap", "calories": 270, "unit": "piece" },
          { "name": "Egg Wrap", "calories": 220, "unit": "piece" },
          { "name": "Duck Roast", "calories": 310, "unit": "cup" }
        ]
      }
    }
  }