snacks = {
    "healthy_snacks": [
        {"name": "Apple slices with peanut butter", "calories": 200, "unit": "serving"},
        {"name": "Carrot sticks with hummus", "calories": 120, "unit": "serving"},
        {"name": "Banana with almond butter", "calories": 250, "unit": "serving"},
        {"name": "Celery sticks with Greek yogurt dip", "calories": 80, "unit": "serving"},
        {"name": "Mixed berries (blueberries, strawberries, raspberries)", "calories": 60, "unit": "cup"},
        {"name": "Sliced pear with ricotta", "calories": 150, "unit": "serving"},
        {"name": "Cherry tomatoes with balsamic glaze", "calories": 50, "unit": "serving"},
        {"name": "Steamed edamame with sea salt", "calories": 120, "unit": "cup"},
        {"name": "Avocado on rice cakes", "calories": 200, "unit": "serving"},
        {"name": "Greek yogurt with honey and granola", "calories": 250, "unit": "cup"},
        {"name": "Cottage cheese with pineapple", "calories": 150, "unit": "cup"},
        {"name": "Cheese cubes with whole-grain crackers", "calories": 200, "unit": "serving"},
        {"name": "Skyr (Icelandic yogurt) with berries", "calories": 130, "unit": "cup"},
        {"name": "String cheese with almonds", "calories": 180, "unit": "serving"},
        {"name": "Low-fat milk smoothie with banana", "calories": 200, "unit": "cup"},
        {"name": "Almonds with dark chocolate chips", "calories": 200, "unit": "serving"},
        {"name": "Trail mix (nuts, seeds, dried fruit)", "calories": 150, "unit": "serving"},
        {"name": "Peanut butter on whole-wheat toast", "calories": 250, "unit": "serving"},
        {"name": "Chia seed pudding with almond milk", "calories": 180, "unit": "cup"},
        {"name": "Sunflower seeds with dried cranberries", "calories": 150, "unit": "serving"},
        {"name": "Dates stuffed with almond butter", "calories": 200, "unit": "serving"},
        {"name": "Walnuts with apple slices", "calories": 220, "unit": "serving"},
        {"name": "Flaxseed crackers with cashew butter", "calories": 180, "unit": "serving"},
        {"name": "Cashew butter with banana slices", "calories": 250, "unit": "serving"},
        {"name": "Oatmeal with cinnamon and berries", "calories": 200, "unit": "cup"},
        {"name": "Popcorn (air-popped, light seasoning)", "calories": 30, "unit": "cup"},
        {"name": "Roasted chickpeas", "calories": 130, "unit": "cup"},
        {"name": "Mini whole-wheat wraps with veggies", "calories": 150, "unit": "piece"},
        {"name": "Quinoa salad cups", "calories": 180, "unit": "cup"},
        {"name": "Lentil soup in a mug", "calories": 150, "unit": "cup"},
        {"name": "Whole-grain toast with mashed avocado", "calories": 250, "unit": "serving"},
        {"name": "Brown rice cakes with cottage cheese", "calories": 150, "unit": "serving"},
        {"name": "Muesli with almond milk", "calories": 200, "unit": "cup"},
        {"name": "Sweet potato toast (sliced, toasted sweet potato)", "calories": 100, "unit": "slice"},
        {"name": "Protein balls (oats, peanut butter, honey)", "calories": 150, "unit": "piece"},
        {"name": "Dark chocolate-dipped strawberries", "calories": 100, "unit": "serving"},
        {"name": "Fruit and nut bars (like Larabars)", "calories": 200, "unit": "bar"},
        {"name": "Smoothie bowl with seeds and fruits", "calories": 300, "unit": "bowl"},
        {"name": "No-bake energy bites", "calories": 150, "unit": "piece"},
        {"name": "Greek yogurt and matcha parfait", "calories": 200, "unit": "cup"},
        {"name": "Cold oatmeal with fruit (overnight oats)", "calories": 250, "unit": "cup"},
        {"name": "Watermelon cubes with feta and mint", "calories": 120, "unit": "cup"},
        {"name": "Baked zucchini chips with yogurt dip", "calories": 100, "unit": "serving"}
    ],
    "veg_snacks": [
        {"name": "Sprouts Salad", "calories": 80, "unit": "cup"},
        {"name": "Fruit Bowl", "calories": 100, "unit": "cup"},
        {"name": "Vegetable Salad", "calories": 50, "unit": "cup"},
        {"name": "Cucumber", "calories": 15, "unit": "cup"},
        {"name": "Carrot Sticks", "calories": 25, "unit": "serving"},
        {"name": "Tender Coconut", "calories": 45, "unit": "cup"},
        {"name": "Peanut Chikki", "calories": 70, "unit": "piece"},
        {"name": "Roasted Peanuts", "calories": 160, "unit": "serving"},
        {"name": "Roasted Chana", "calories": 140, "unit": "cup"},
        {"name": "Dry Fruits Mix", "calories": 150, "unit": "serving"},
        {"name": "Trail Mix (Nuts + Seeds)", "calories": 150, "unit": "serving"},
        {"name": "Fox Nuts (Makhana)", "calories": 100, "unit": "cup"},
        {"name": "Wheat Rusk", "calories": 50, "unit": "piece"},
        {"name": "Oats Biscuit", "calories": 60, "unit": "piece"},
        {"name": "Millet Ladoo", "calories": 120, "unit": "piece"},
        {"name": "Millet Chips", "calories": 130, "unit": "serving"},
        {"name": "Khakhra", "calories": 40, "unit": "piece"},
        {"name": "Dhokla", "calories": 150, "unit": "piece"},
        {"name": "Poha Chivda (Low Oil)", "calories": 120, "unit": "cup"},
        {"name": "Popcorn (Air-popped)", "calories": 30, "unit": "cup"},
        {"name": "Veg Sandwich (Whole Wheat, Low Oil)", "calories": 250, "unit": "serving"},
        {"name": "Peanut Butter Sandwich", "calories": 300, "unit": "serving"},
        {"name": "Wheat Crackers", "calories": 80, "unit": "serving"},
        {"name": "Moong Dal Chilla", "calories": 160, "unit": "piece"},
        {"name": "Besan Chilla", "calories": 180, "unit": "piece"},
        {"name": "Soya Chunks (Roasted)", "calories": 150, "unit": "cup"},
        {"name": "Paneer Tikka", "calories": 200, "unit": "serving"},
        {"name": "Tofu Stir Fry", "calories": 120, "unit": "cup"},
        {"name": "Greek Yogurt Cup", "calories": 130, "unit": "cup"},
        {"name": "Sprouted Moong Bowl", "calories": 100, "unit": "cup"}
    ],
    "non_veg_snacks": [
        {"name": "Boiled Eggs", "calories": 70, "unit": "egg"},
        {"name": "Omelette", "calories": 200, "unit": "serving"},
        {"name": "Egg Bhurji", "calories": 220, "unit": "cup"},
        {"name": "Egg Sandwich", "calories": 300, "unit": "serving"},
        {"name": "Chicken Sandwich", "calories": 400, "unit": "serving"},
        {"name": "Chicken Cutlet (Low Oil)", "calories": 250, "unit": "piece"},
        {"name": "Grilled Chicken Strips", "calories": 200, "unit": "serving"},
        {"name": "Chicken Sausage (Low Fat)", "calories": 150, "unit": "piece"},
        {"name": "Tuna Sandwich", "calories": 380, "unit": "serving"},
        {"name": "Fish Cutlet (Low Oil)", "calories": 200, "unit": "piece"},
        {"name": "Prawn Salad Bowl", "calories": 180, "unit": "cup"}
    ],
    "beverages": {
        "moderate_calories": [
            {"name": "Tender Coconut Water", "calories": 45, "unit": "cup"},
            {"name": "Buttermilk (Chaas)", "calories": 40, "unit": "cup"},
            {"name": "Salted Lassi", "calories": 100, "unit": "cup"},
            {"name": "Fresh Lime Soda (without sugar)", "calories": 5, "unit": "cup"},
            {"name": "Masala Chai (less sugar)", "calories": 50, "unit": "cup"},
            {"name": "Hot Chocolate (light)", "calories": 120, "unit": "cup"},
            {"name": "Badam Milk (light version)", "calories": 150, "unit": "cup"},
            {"name": "Protein Shake (Whey/Plant Protein)", "calories": 150, "unit": "cup"},
            {"name": "Cold Coffee (low sugar)", "calories": 100, "unit": "cup"},
            {"name": "Fruit Smoothie (Banana, Papaya, Berry, low sugar)", "calories": 150, "unit": "cup"},
            {"name": "Milk (Hot/Cold)", "calories": 150, "unit": "cup"},
            {"name": "Turmeric Milk (Haldi Milk)", "calories": 160, "unit": "cup"}
        ]
    }
}
