western_food = {
    "breakfast": {
      "base_items": {
        "core_items": [
          { "name": "Toast", "calories": 70, "unit": "slice" },
          { "name": "White Bread", "calories": 70, "unit": "slice" },
          { "name": "Whole Wheat Bread", "calories": 80, "unit": "slice" },
          { "name": "Sourdough Bread", "calories": 80, "unit": "slice" },
          { "name": "Bagel", "calories": 250, "unit": "piece" },
          { "name": "English Muffin", "calories": 130, "unit": "piece" },
          { "name": "Croissant", "calories": 230, "unit": "piece" },
          { "name": "Pancakes", "calories": 90, "unit": "piece" },
          { "name": "Waffles", "calories": 200, "unit": "piece" },
          { "name": "French Toast", "calories": 180, "unit": "slice" },
          { "name": "Hash Browns", "calories": 150, "unit": "serving" },
          { "name": "Home Fries", "calories": 200, "unit": "cup" },
          { "name": "Breakfast Potatoes", "calories": 180, "unit": "cup" },
          { "name": "Scrambled Eggs", "calories": 90, "unit": "egg" },
          { "name": "Fried Eggs", "calories": 90, "unit": "egg" },
          { "name": "Poached Eggs", "calories": 70, "unit": "egg" },
          { "name": "Boiled Eggs", "calories": 70, "unit": "egg" },
          { "name": "Omelette", "calories": 200, "unit": "serving" },
          { "name": "Eggs Benedict", "calories": 350, "unit": "serving" },
          { "name": "Breakfast Burrito", "calories": 300, "unit": "piece" },
          { "name": "Breakfast Sandwich", "calories": 350, "unit": "piece" },
          { "name": "Granola", "calories": 200, "unit": "cup" },
          { "name": "Cereal", "calories": 150, "unit": "cup" },
          { "name": "Oatmeal", "calories": 150, "unit": "cup" },
          { "name": "Porridge", "calories": 150, "unit": "cup" },
          { "name": "Yogurt", "calories": 100, "unit": "cup" },
          { "name": "Greek Yogurt", "calories": 130, "unit": "cup" }
        ],
        "complete_dishes": [
          { "name": "Full English Breakfast", "calories": 800, "unit": "plate" },
          { "name": "Continental Breakfast", "calories": 400, "unit": "plate" },
          { "name": "American Breakfast", "calories": 600, "unit": "plate" },
          { "name": "Breakfast Bowl", "calories": 350, "unit": "bowl" },
          { "name": "Avocado Toast", "calories": 250, "unit": "serving" },
          { "name": "Eggs on Toast", "calories": 230, "unit": "serving" },
          { "name": "Breakfast Wrap", "calories": 320, "unit": "piece" }
        ]
      },
      "veg_items": {
        "gravy": [
          { "name": "Hollandaise Sauce", "calories": 100, "unit": "tbsp" },
          { "name": "Maple Syrup", "calories": 50, "unit": "tbsp" },
          { "name": "Honey", "calories": 60, "unit": "tbsp" },
          { "name": "Jam", "calories": 50, "unit": "tbsp" },
          { "name": "Marmalade", "calories": 50, "unit": "tbsp" },
          { "name": "Peanut Butter", "calories": 95, "unit": "tbsp" },
          { "name": "Almond Butter", "calories": 100, "unit": "tbsp" },
          { "name": "Cream Cheese", "calories": 50, "unit": "tbsp" },
          { "name": "Butter", "calories": 100, "unit": "tbsp" },
          { "name": "Fruit Compote", "calories": 60, "unit": "tbsp" },
          { "name": "Berry Sauce", "calories": 40, "unit": "tbsp" },
          { "name": "Hollandaise Sauce (Veg)", "calories": 100, "unit": "tbsp" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Bacon", "calories": 45, "unit": "slice" },
          { "name": "Sausages", "calories": 200, "unit": "piece" },
          { "name": "Ham", "calories": 50, "unit": "slice" },
          { "name": "Canadian Bacon", "calories": 60, "unit": "slice" },
          { "name": "Turkey Sausage", "calories": 150, "unit": "piece" },
          { "name": "Chicken Sausage", "calories": 180, "unit": "piece" },
          { "name": "Smoked Salmon", "calories": 100, "unit": "oz" },
          { "name": "Eggs Benedict with Ham", "calories": 400, "unit": "serving" },
          { "name": "Breakfast Sausage Gravy", "calories": 200, "unit": "cup" },
          { "name": "Bacon Gravy", "calories": 180, "unit": "cup" }
        ]
      }
    },
    "lunch": {
      "base_items": {
        "core_items": [
          { "name": "Sandwich Bread", "calories": 70, "unit": "slice" },
          { "name": "Whole Wheat Bread", "calories": 80, "unit": "slice" },
          { "name": "Sourdough Bread", "calories": 80, "unit": "slice" },
          { "name": "Rye Bread", "calories": 80, "unit": "slice" },
          { "name": "Ciabatta", "calories": 100, "unit": "slice" },
          { "name": "Focaccia", "calories": 120, "unit": "slice" },
          { "name": "Baguette", "calories": 90, "unit": "slice" },
          { "name": "Wrap", "calories": 150, "unit": "piece" },
          { "name": "Tortilla", "calories": 100, "unit": "piece" },
          { "name": "Pita Bread", "calories": 80, "unit": "piece" },
          { "name": "Burger Bun", "calories": 120, "unit": "piece" },
          { "name": "Hot Dog Bun", "calories": 100, "unit": "piece" },
          { "name": "Rice", "calories": 200, "unit": "cup" },
          { "name": "Pasta", "calories": 200, "unit": "cup" },
          { "name": "Spaghetti", "calories": 200, "unit": "cup" },
          { "name": "Penne", "calories": 200, "unit": "cup" },
          { "name": "Fusilli", "calories": 200, "unit": "cup" },
          { "name": "Macaroni", "calories": 200, "unit": "cup" },
          { "name": "Fettuccine", "calories": 200, "unit": "cup" },
          { "name": "Linguine", "calories": 200, "unit": "cup" },
          { "name": "Risotto", "calories": 250, "unit": "cup" },
          { "name": "Quinoa", "calories": 220, "unit": "cup" },
          { "name": "Couscous", "calories": 200, "unit": "cup" },
          { "name": "Salad Greens", "calories": 10, "unit": "cup" },
          { "name": "Mixed Greens", "calories": 10, "unit": "cup" },
          { "name": "Lettuce", "calories": 5, "unit": "cup" },
          { "name": "Spinach", "calories": 7, "unit": "cup" },
          { "name": "Arugula", "calories": 5, "unit": "cup" }
        ],
        "complete_dishes": [
          { "name": "Caesar Salad", "calories": 250, "unit": "serving" },
          { "name": "Greek Salad", "calories": 200, "unit": "serving" },
          { "name": "Cobb Salad", "calories": 400, "unit": "serving" },
          { "name": "Garden Salad", "calories": 50, "unit": "serving" },
          { "name": "Chef Salad", "calories": 350, "unit": "serving" },
          { "name": "Waldorf Salad", "calories": 300, "unit": "serving" },
          { "name": "Pasta Salad", "calories": 300, "unit": "cup" },
          { "name": "Quinoa Salad", "calories": 250, "unit": "cup" },
          { "name": "Couscous Salad", "calories": 250, "unit": "cup" },
          { "name": "Soup and Salad", "calories": 300, "unit": "serving" },
          { "name": "Sandwich Combo", "calories": 500, "unit": "serving" },
          { "name": "Burger Combo", "calories": 700, "unit": "serving" }
        ]
      },
      "veg_items": {
        "dry": [
          { "name": "Grilled Vegetables", "calories": 100, "unit": "cup" },
          { "name": "Roasted Vegetables", "calories": 120, "unit": "cup" },
          { "name": "Vegetable Skewers", "calories": 150, "unit": "serving" },
          { "name": "Stuffed Bell Peppers", "calories": 200, "unit": "piece" },
          { "name": "Vegetable Fritters", "calories": 150, "unit": "piece" },
          { "name": "Zucchini Fritters", "calories": 120, "unit": "piece" },
          { "name": "Corn Fritters", "calories": 180, "unit": "piece" },
          { "name": "Vegetable Tempura", "calories": 200, "unit": "serving" },
          { "name": "Fried Zucchini", "calories": 150, "unit": "cup" },
          { "name": "Breaded Mushrooms", "calories": 180, "unit": "cup" },
          { "name": "Onion Rings", "calories": 200, "unit": "serving" },
          { "name": "French Fries", "calories": 250, "unit": "serving" },
          { "name": "Sweet Potato Fries", "calories": 200, "unit": "serving" },
          { "name": "Hash Browns", "calories": 150, "unit": "serving" },
          { "name": "Vegetable Chips", "calories": 150, "unit": "serving" }
        ],
        "gravy": [
          { "name": "Vegetable Soup", "calories": 100, "unit": "cup" },
          { "name": "Tomato Soup", "calories": 120, "unit": "cup" },
          { "name": "Minestrone", "calories": 150, "unit": "cup" },
          { "name": "Cream of Mushroom Soup", "calories": 200, "unit": "cup" },
          { "name": "Broccoli Cheddar Soup", "calories": 250, "unit": "cup" },
          { "name": "Vegetable Stew", "calories": 150, "unit": "cup" },
          { "name": "Ratatouille", "calories": 120, "unit": "cup" },
          { "name": "Pasta Primavera", "calories": 350, "unit": "cup" },
          { "name": "Vegetable Lasagna", "calories": 300, "unit": "serving" },
          { "name": "Eggplant Parmesan", "calories": 350, "unit": "serving" },
          { "name": "Vegetable Risotto", "calories": 300, "unit": "cup" },
          { "name": "Mac and Cheese", "calories": 400, "unit": "cup" },
          { "name": "Alfredo Pasta", "calories": 450, "unit": "cup" },
          { "name": "Marinara Pasta", "calories": 300, "unit": "cup" },
          { "name": "Pesto Pasta", "calories": 400, "unit": "cup" },
          { "name": "Vegetable Curry (Western Style)", "calories": 200, "unit": "cup" },
          { "name": "Vegetable Stir Fry", "calories": 150, "unit": "cup" },
          { "name": "Vegetable Casserole", "calories": 250, "unit": "cup" },
          { "name": "Stuffed Bell Peppers (Gravy)", "calories": 250, "unit": "piece" },
          { "name": "Vegetable Pot Pie", "calories": 350, "unit": "serving" },
          { "name": "Vegetable Shepherd's Pie", "calories": 300, "unit": "serving" }
        ]
      },
      "non_veg_items": {
        "dry": [
          { "name": "Grilled Chicken", "calories": 290, "unit": "serving" },
          { "name": "Fried Chicken", "calories": 350, "unit": "serving" },
          { "name": "Chicken Wings", "calories": 200, "unit": "piece" },
          { "name": "Chicken Tenders", "calories": 300, "unit": "serving" },
          { "name": "Chicken Nuggets", "calories": 250, "unit": "serving" },
          { "name": "Grilled Fish", "calories": 200, "unit": "serving" },
          { "name": "Fried Fish", "calories": 250, "unit": "serving" },
          { "name": "Fish and Chips", "calories": 500, "unit": "serving" },
          { "name": "Grilled Salmon", "calories": 280, "unit": "serving" },
          { "name": "Tuna Steak", "calories": 250, "unit": "serving" },
          { "name": "Shrimp Skewers", "calories": 200, "unit": "serving" },
          { "name": "Grilled Shrimp", "calories": 180, "unit": "serving" },
          { "name": "Fried Shrimp", "calories": 250, "unit": "serving" },
          { "name": "Calamari", "calories": 200, "unit": "serving" },
          { "name": "Chicken Sandwich", "calories": 400, "unit": "serving" },
          { "name": "Turkey Sandwich", "calories": 350, "unit": "serving" },
          { "name": "Ham Sandwich", "calories": 320, "unit": "serving" },
          { "name": "Tuna Sandwich", "calories": 380, "unit": "serving" },
          { "name": "Chicken Burger", "calories": 450, "unit": "serving" },
          { "name": "Turkey Burger", "calories": 400, "unit": "serving" },
          { "name": "Fish Burger", "calories": 420, "unit": "serving" },
          { "name": "Chicken Wrap", "calories": 400, "unit": "piece" },
          { "name": "Turkey Wrap", "calories": 350, "unit": "piece" },
          { "name": "Tuna Wrap", "calories": 380, "unit": "piece" }
        ],
        "gravy": [
          { "name": "Chicken Soup", "calories": 150, "unit": "cup" },
          { "name": "Chicken Noodle Soup", "calories": 200, "unit": "cup" },
          { "name": "Cream of Chicken Soup", "calories": 250, "unit": "cup" },
          { "name": "Beef Stew", "calories": 300, "unit": "cup" },
          { "name": "Chicken Stew", "calories": 250, "unit": "cup" },
          { "name": "Seafood Chowder", "calories": 280, "unit": "cup" },
          { "name": "Clam Chowder", "calories": 250, "unit": "cup" },
          { "name": "Fish Chowder", "calories": 240, "unit": "cup" },
          { "name": "Chicken Pot Pie", "calories": 400, "unit": "serving" },
          { "name": "Beef Pot Pie", "calories": 450, "unit": "serving" },
          { "name": "Shepherd's Pie", "calories": 350, "unit": "serving" },
          { "name": "Chicken Casserole", "calories": 350, "unit": "cup" },
          { "name": "Tuna Casserole", "calories": 300, "unit": "cup" },
          { "name": "Chicken Alfredo", "calories": 500, "unit": "cup" },
          { "name": "Chicken Pasta", "calories": 450, "unit": "cup" },
          { "name": "Seafood Pasta", "calories": 400, "unit": "cup" },
          { "name": "Shrimp Scampi", "calories": 350, "unit": "cup" },
          { "name": "Chicken Risotto", "calories": 400, "unit": "cup" },
          { "name": "Seafood Risotto", "calories": 380, "unit": "cup" },
          { "name": "Chicken Curry (Western Style)", "calories": 300, "unit": "cup" },
          { "name": "Beef Stroganoff", "calories": 400, "unit": "cup" },
          { "name": "Chicken Stroganoff", "calories": 350, "unit": "cup" },
          { "name": "Coq au Vin", "calories": 350, "unit": "cup" },
          { "name": "Chicken Marsala", "calories": 400, "unit": "cup" },
          { "name": "Chicken Piccata", "calories": 350, "unit": "cup" },
          { "name": "Fish Curry (Western Style)", "calories": 280, "unit": "cup" },
          { "name": "Lobster Bisque", "calories": 300, "unit": "cup" },
          { "name": "Crab Bisque", "calories": 280, "unit": "cup" }
        ]
      }
    },
    "dinner": {
      "base_items": {
        "core_items": [
          { "name": "Mashed Potatoes", "calories": 200, "unit": "cup" },
          { "name": "Baked Potato", "calories": 220, "unit": "piece" },
          { "name": "Roasted Potatoes", "calories": 180, "unit": "cup" },
          { "name": "French Fries", "calories": 250, "unit": "serving" },
          { "name": "Sweet Potato", "calories": 180, "unit": "piece" },
          { "name": "Rice", "calories": 200, "unit": "cup" },
          { "name": "Wild Rice", "calories": 170, "unit": "cup" },
          { "name": "Brown Rice", "calories": 215, "unit": "cup" },
          { "name": "Pasta", "calories": 200, "unit": "cup" },
          { "name": "Spaghetti", "calories": 200, "unit": "cup" },
          { "name": "Penne", "calories": 200, "unit": "cup" },
          { "name": "Fettuccine", "calories": 200, "unit": "cup" },
          { "name": "Linguine", "calories": 200, "unit": "cup" },
          { "name": "Rigatoni", "calories": 200, "unit": "cup" },
          { "name": "Risotto", "calories": 250, "unit": "cup" },
          { "name": "Quinoa", "calories": 220, "unit": "cup" },
          { "name": "Couscous", "calories": 200, "unit": "cup" },
          { "name": "Polenta", "calories": 150, "unit": "cup" },
          { "name": "Bread", "calories": 70, "unit": "slice" },
          { "name": "Garlic Bread", "calories": 150, "unit": "slice" },
          { "name": "Dinner Rolls", "calories": 80, "unit": "piece" },
          { "name": "Biscuits", "calories": 100, "unit": "piece" }
        ],
        "complete_dishes": [
          { "name": "Pizza", "calories": 300, "unit": "slice" },
          { "name": "Margherita Pizza", "calories": 280, "unit": "slice" },
          { "name": "Vegetable Pizza", "calories": 290, "unit": "slice" },
          { "name": "Pepperoni Pizza", "calories": 320, "unit": "slice" },
          { "name": "Chicken Pizza", "calories": 340, "unit": "slice" },
          { "name": "BBQ Chicken Pizza", "calories": 350, "unit": "slice" },
          { "name": "Hawaiian Pizza", "calories": 330, "unit": "slice" },
          { "name": "Lasagna", "calories": 400, "unit": "serving" },
          { "name": "Vegetable Lasagna", "calories": 300, "unit": "serving" },
          { "name": "Chicken Lasagna", "calories": 450, "unit": "serving" },
          { "name": "Beef Lasagna", "calories": 500, "unit": "serving" },
          { "name": "Spaghetti and Meatballs", "calories": 500, "unit": "serving" },
          { "name": "Fettuccine Alfredo", "calories": 600, "unit": "serving" },
          { "name": "Pasta Carbonara", "calories": 550, "unit": "serving" },
          { "name": "Penne Arrabbiata", "calories": 350, "unit": "serving" }
        ]
      },
      "veg_items": {
        "dry": [
          { "name": "Grilled Vegetables", "calories": 100, "unit": "cup" },
          { "name": "Roasted Vegetables", "calories": 120, "unit": "cup" },
          { "name": "Steamed Vegetables", "calories": 50, "unit": "cup" },
          { "name": "Sautéed Vegetables", "calories": 120, "unit": "cup" },
          { "name": "Vegetable Medley", "calories": 100, "unit": "cup" },
          { "name": "Asparagus", "calories": 30, "unit": "cup" },
          { "name": "Broccoli", "calories": 30, "unit": "cup" },
          { "name": "Brussels Sprouts", "calories": 40, "unit": "cup" },
          { "name": "Green Beans", "calories": 30, "unit": "cup" },
          { "name": "Carrots", "calories": 50, "unit": "cup" },
          { "name": "Cauliflower", "calories": 30, "unit": "cup" },
          { "name": "Zucchini", "calories": 20, "unit": "cup" },
          { "name": "Eggplant", "calories": 35, "unit": "cup" },
          { "name": "Mushrooms", "calories": 20, "unit": "cup" },
          { "name": "Stuffed Bell Peppers", "calories": 200, "unit": "piece" },
          { "name": "Vegetable Skewers", "calories": 150, "unit": "serving" },
          { "name": "Ratatouille", "calories": 120, "unit": "cup" },
          { "name": "Caprese Salad", "calories": 200, "unit": "serving" },
          { "name": "Greek Salad", "calories": 200, "unit": "serving" }
        ],
        "gravy": [
          { "name": "Vegetable Risotto", "calories": 300, "unit": "cup" },
          { "name": "Mushroom Risotto", "calories": 320, "unit": "cup" },
          { "name": "Vegetable Pasta", "calories": 350, "unit": "cup" },
          { "name": "Pasta Primavera", "calories": 350, "unit": "cup" },
          { "name": "Vegetable Lasagna", "calories": 300, "unit": "serving" },
          { "name": "Eggplant Parmesan", "calories": 350, "unit": "serving" },
          { "name": "Vegetable Casserole", "calories": 250, "unit": "cup" },
          { "name": "Vegetable Pot Pie", "calories": 350, "unit": "serving" },
          { "name": "Vegetable Shepherd's Pie", "calories": 300, "unit": "serving" },
          { "name": "Vegetable Stew", "calories": 150, "unit": "cup" },
          { "name": "Ratatouille", "calories": 120, "unit": "cup" },
          { "name": "Vegetable Curry (Western Style)", "calories": 200, "unit": "cup" },
          { "name": "Vegetable Stir Fry", "calories": 150, "unit": "cup" },
          { "name": "Creamed Spinach", "calories": 200, "unit": "cup" },
          { "name": "Creamed Corn", "calories": 180, "unit": "cup" },
          { "name": "Green Bean Casserole", "calories": 200, "unit": "cup" },
          { "name": "Mac and Cheese", "calories": 400, "unit": "cup" },
          { "name": "Alfredo Pasta", "calories": 450, "unit": "cup" },
          { "name": "Marinara Pasta", "calories": 300, "unit": "cup" },
          { "name": "Pesto Pasta", "calories": 400, "unit": "cup" },
          { "name": "Aglio e Olio", "calories": 350, "unit": "cup" },
          { "name": "Vegetable Soup", "calories": 100, "unit": "cup" },
          { "name": "Minestrone", "calories": 150, "unit": "cup" },
          { "name": "Tomato Basil Soup", "calories": 120, "unit": "cup" },
          { "name": "Broccoli Cheddar Soup", "calories": 250, "unit": "cup" }
        ]
      },
      "non_veg_items": {
        "dry": [
          { "name": "Grilled Steak", "calories": 400, "unit": "serving" },
          { "name": "Pan-Seared Steak", "calories": 400, "unit": "serving" },
          { "name": "Filet Mignon", "calories": 350, "unit": "serving" },
          { "name": "Ribeye Steak", "calories": 450, "unit": "serving" },
          { "name": "Sirloin Steak", "calories": 380, "unit": "serving" },
          { "name": "T-Bone Steak", "calories": 450, "unit": "serving" },
          { "name": "Porterhouse Steak", "calories": 500, "unit": "serving" },
          { "name": "Grilled Chicken Breast", "calories": 250, "unit": "serving" },
          { "name": "Roasted Chicken", "calories": 300, "unit": "serving" },
          { "name": "Fried Chicken", "calories": 350, "unit": "serving" },
          { "name": "Chicken Wings", "calories": 200, "unit": "piece" },
          { "name": "Grilled Salmon", "calories": 280, "unit": "serving" },
          { "name": "Pan-Seared Salmon", "calories": 280, "unit": "serving" },
          { "name": "Baked Salmon", "calories": 250, "unit": "serving" },
          { "name": "Grilled Tuna", "calories": 250, "unit": "serving" },
          { "name": "Pan-Seared Tuna", "calories": 250, "unit": "serving" },
          { "name": "Grilled Shrimp", "calories": 180, "unit": "serving" },
          { "name": "Pan-Seared Shrimp", "calories": 180, "unit": "serving" },
          { "name": "Grilled Scallops", "calories": 200, "unit": "serving" },
          { "name": "Pan-Seared Scallops", "calories": 200, "unit": "serving" },
          { "name": "Lobster Tail", "calories": 300, "unit": "serving" },
          { "name": "Crab Legs", "calories": 200, "unit": "serving" },
          { "name": "Roast Beef", "calories": 350, "unit": "serving" },
          { "name": "Prime Rib", "calories": 500, "unit": "serving" },
          { "name": "Beef Tenderloin", "calories": 400, "unit": "serving" },
          { "name": "Lamb Chops", "calories": 400, "unit": "serving" },
          { "name": "Pork Chops", "calories": 350, "unit": "serving" },
          { "name": "Grilled Pork", "calories": 350, "unit": "serving" },
          { "name": "BBQ Ribs", "calories": 500, "unit": "serving" },
          { "name": "Chicken Thighs", "calories": 300, "unit": "serving" },
          { "name": "Drumsticks", "calories": 250, "unit": "serving" },
          { "name": "Turkey Breast", "calories": 250, "unit": "serving" },
          { "name": "Duck Breast", "calories": 350, "unit": "serving" }
        ],
        "gravy": [
          { "name": "Beef Stew", "calories": 300, "unit": "cup" },
          { "name": "Chicken Stew", "calories": 250, "unit": "cup" },
          { "name": "Lamb Stew", "calories": 320, "unit": "cup" },
          { "name": "Coq au Vin", "calories": 350, "unit": "cup" },
          { "name": "Beef Bourguignon", "calories": 400, "unit": "cup" },
          { "name": "Chicken Marsala", "calories": 400, "unit": "cup" },
          { "name": "Chicken Piccata", "calories": 350, "unit": "cup" },
          { "name": "Chicken Cordon Bleu", "calories": 450, "unit": "serving" },
          { "name": "Chicken Parmesan", "calories": 500, "unit": "serving" },
          { "name": "Chicken Alfredo", "calories": 500, "unit": "cup" },
          { "name": "Chicken Pasta", "calories": 450, "unit": "cup" },
          { "name": "Seafood Pasta", "calories": 400, "unit": "cup" },
          { "name": "Shrimp Scampi", "calories": 350, "unit": "cup" },
          { "name": "Lobster Pasta", "calories": 450, "unit": "cup" },
          { "name": "Crab Pasta", "calories": 400, "unit": "cup" },
          { "name": "Chicken Risotto", "calories": 400, "unit": "cup" },
          { "name": "Seafood Risotto", "calories": 380, "unit": "cup" },
          { "name": "Mushroom Risotto with Chicken", "calories": 420, "unit": "cup" },
          { "name": "Chicken Pot Pie", "calories": 400, "unit": "serving" },
          { "name": "Beef Pot Pie", "calories": 450, "unit": "serving" },
          { "name": "Shepherd's Pie", "calories": 350, "unit": "serving" },
          { "name": "Chicken Casserole", "calories": 350, "unit": "cup" },
          { "name": "Tuna Casserole", "calories": 300, "unit": "cup" },
          { "name": "Beef Stroganoff", "calories": 400, "unit": "cup" },
          { "name": "Chicken Stroganoff", "calories": 350, "unit": "cup" },
          { "name": "Chicken Curry (Western Style)", "calories": 300, "unit": "cup" },
          { "name": "Beef Curry (Western Style)", "calories": 350, "unit": "cup" },
          { "name": "Fish Curry (Western Style)", "calories": 280, "unit": "cup" },
          { "name": "Seafood Chowder", "calories": 280, "unit": "cup" },
          { "name": "Clam Chowder", "calories": 250, "unit": "cup" },
          { "name": "Lobster Bisque", "calories": 300, "unit": "cup" },
          { "name": "Crab Bisque", "calories": 280, "unit": "cup" },
          { "name": "Chicken Noodle Soup", "calories": 200, "unit": "cup" },
          { "name": "Beef Soup", "calories": 250, "unit": "cup" },
          { "name": "French Onion Soup", "calories": 300, "unit": "cup" },
          { "name": "Chicken Fricassee", "calories": 350, "unit": "cup" },
          { "name": "Beef Ragu", "calories": 400, "unit": "cup" },
          { "name": "Osso Buco", "calories": 450, "unit": "serving" },
          { "name": "Braised Short Ribs", "calories": 500, "unit": "serving" },
          { "name": "Chicken Tagine", "calories": 350, "unit": "cup" },
          { "name": "Lamb Tagine", "calories": 380, "unit": "cup" }
        ]
      }
    }
  }