kerala_food = {
    "breakfast": {
      "base_items": {
        "veg": {
          "core_items": [
            { "name": "Idli", "calories": 45, "unit": "piece" },
            { "name": "Dosa", "calories": 90, "unit": "piece" },
            { "name": "Masala Dosa", "calories": 275, "unit": "piece" },
            { "name": "Ghee Roast Dosa", "calories": 320, "unit": "piece" },
            { "name": "Rava Dosa", "calories": 200, "unit": "piece" },
            { "name": "Wheat Dosa", "calories": 100, "unit": "piece" },
            { "name": "Ragi Dosa", "calories": 120, "unit": "piece" },
            { "name": "Neer Dosa", "calories": 80, "unit": "piece" },
            { "name": "Onion Uthappam", "calories": 180, "unit": "piece" },
            { "name": "Plain Uthappam", "calories": 150, "unit": "piece" },
            { "name": "Appam", "calories": 95, "unit": "piece" },
            { "name": "Idiyappam", "calories": 65, "unit": "piece" },
            { "name": "Puttu", "calories": 275, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Poori", "calories": 150, "unit": "piece" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Bread", "calories": 70, "unit": "slice" },
            { "name": "Pav", "calories": 80, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Upma", "calories": 225, "unit": "cup" },
            { "name": "Semiya Upma", "calories": 250, "unit": "cup" },
            { "name": "Aval Upma", "calories": 200, "unit": "cup" },
            { "name": "Pongal", "calories": 220, "unit": "cup" },
            { "name": "Ela Ada", "calories": 150, "unit": "piece" },
            { "name": "Kappa", "calories": 180, "unit": "cup" },
            { "name": "Banana", "calories": 105, "unit": "medium" }
          ]
        },
        "non_veg": {
          "core_items": [
            { "name": "Idli", "calories": 45, "unit": "piece" },
            { "name": "Dosa", "calories": 90, "unit": "piece" },
            { "name": "Masala Dosa", "calories": 275, "unit": "piece" },
            { "name": "Ghee Roast Dosa", "calories": 320, "unit": "piece" },
            { "name": "Rava Dosa", "calories": 200, "unit": "piece" },
            { "name": "Wheat Dosa", "calories": 100, "unit": "piece" },
            { "name": "Ragi Dosa", "calories": 120, "unit": "piece" },
            { "name": "Neer Dosa", "calories": 80, "unit": "piece" },
            { "name": "Onion Uthappam", "calories": 180, "unit": "piece" },
            { "name": "Plain Uthappam", "calories": 150, "unit": "piece" },
            { "name": "Appam", "calories": 95, "unit": "piece" },
            { "name": "Idiyappam", "calories": 65, "unit": "piece" },
            { "name": "Puttu", "calories": 275, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Poori", "calories": 150, "unit": "piece" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Bread", "calories": 70, "unit": "slice" },
            { "name": "Pav", "calories": 80, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Upma", "calories": 225, "unit": "cup" },
            { "name": "Semiya Upma", "calories": 250, "unit": "cup" },
            { "name": "Aval Upma", "calories": 200, "unit": "cup" },
            { "name": "Pongal", "calories": 220, "unit": "cup" },
            { "name": "Ela Ada", "calories": 150, "unit": "piece" },
            { "name": "Kappa", "calories": 180, "unit": "cup" },
            { "name": "Banana", "calories": 105, "unit": "medium" }
          ]
        },
        "vegan": {
          "core_items": [
            { "name": "Idli ", "calories": 40, "unit": "piece" },
            { "name": "Dosa ", "calories": 85, "unit": "piece" },
            { "name": "Masala Dosa ", "calories": 270, "unit": "piece" },
            { "name": "Ghee Roast Dosa ", "calories": 315, "unit": "piece" },
            { "name": "Rava Dosa ", "calories": 195, "unit": "piece" },
            { "name": "Wheat Dosa ", "calories": 95, "unit": "piece" },
            { "name": "Ragi Dosa ", "calories": 115, "unit": "piece" },
            { "name": "Neer Dosa ", "calories": 75, "unit": "piece" },
            { "name": "Onion Uthappam ", "calories": 175, "unit": "piece" },
            { "name": "Plain Uthappam ", "calories": 145, "unit": "piece" },
            { "name": "Appam ", "calories": 90, "unit": "piece" },
            { "name": "Idiyappam ", "calories": 60, "unit": "piece" },
            { "name": "Puttu ", "calories": 270, "unit": "piece" },
            { "name": "Pathiri ", "calories": 115, "unit": "piece" },
            { "name": "Parotta ", "calories": 270, "unit": "piece" },
            { "name": "Poori ", "calories": 145, "unit": "piece" },
            { "name": "Chapati ", "calories": 105, "unit": "piece" },
            { "name": "Roti ", "calories": 105, "unit": "piece" },
            { "name": "Bread ", "calories": 65, "unit": "slice" },
            { "name": "Pav ", "calories": 75, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Upma ", "calories": 220, "unit": "cup" },
            { "name": "Semiya Upma ", "calories": 245, "unit": "cup" },
            { "name": "Aval Upma ", "calories": 195, "unit": "cup" },
            { "name": "Pongal ", "calories": 215, "unit": "cup" },
            { "name": "Ela Ada ", "calories": 145, "unit": "piece" },
            { "name": "Kappa ", "calories": 175, "unit": "cup" },
            { "name": "Banana ", "calories": 105, "unit": "medium" }
          ]
        }
      },
      "veg_items": {
        "gravy": [
          { "name": "Vegetable Stew", "calories": 0.7, "unit": "gram" },
          { "name": "Kadala Curry", "calories": 1.0, "unit": "gram" },
          { "name": "Sambar", "calories": 0.6, "unit": "gram" },
          { "name": "Coconut Chutney", "calories": 45, "unit": "tbsp" },
          { "name": "Tomato Chutney", "calories": 30, "unit": "tbsp" },
          { "name": "Mint Chutney", "calories": 25, "unit": "tbsp" },
          { "name": "Potato Masala", "calories": 0.9, "unit": "gram" },
          { "name": "Chana Curry", "calories": 0.9, "unit": "gram" },
          { "name": "Coconut Milk", "calories": 50, "unit": "tbsp" },
          { "name": "Mulaku Chammanthi", "calories": 30, "unit": "tbsp" },
          { "name": "Kappa Puzhukku", "calories": 0.8, "unit": "gram" },
          { "name": "Thari Kanji", "calories": 0.5, "unit": "gram" },
          { "name": "Vendakka Stew", "calories": 0.6, "unit": "gram" },
          { "name": "Kumbalanga Stew", "calories": 0.6, "unit": "gram" },
          { "name": "Kappa Vevichathu", "calories": 0.7, "unit": "gram" },
          { "name": "Red Chilli Chutney", "calories": 35, "unit": "tbsp" },
          { "name": "Pazham Kanji", "calories": 0.5, "unit": "gram" },
          { "name": "Coconut Milk Kanji", "calories": 0.6, "unit": "gram" },
          { "name": "Uluva Kanji", "calories": 0.6, "unit": "gram" },
          { "name": "Vegetable Kurma", "calories": 0.7, "unit": "gram" },
          { "name": "Avial", "calories": 0.8, "unit": "gram" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Fish Stew", "calories": 1.1, "unit": "gram" },
          { "name": "Chicken Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Egg Roast", "calories": 0.9, "unit": "gram" },
          { "name": "Egg Dosa", "calories": 180, "unit": "piece" },
          { "name": "Egg Appam", "calories": 150, "unit": "piece" },
          { "name": "Mutta Roast", "calories": 0.9, "unit": "gram" },
          { "name": "Mutta Curry", "calories": 0.8, "unit": "gram" },
          { "name": "Fish Molee", "calories": 1.1, "unit": "gram" },
          { "name": "Chemmeen Roast", "calories": 1.2, "unit": "gram" },
          { "name": "Prawns Stew", "calories": 1.2, "unit": "gram" },
          { "name": "Chicken Kurma", "calories": 1.3, "unit": "gram" },
          { "name": "Egg Masala", "calories": 0.9, "unit": "gram" }
        ]
      },
      "vegan_items": {
        "gravy": [
          { "name": "Vegetable Stew ", "calories": 0.6, "unit": "gram" },
          { "name": "Kadala Curry ", "calories": 1.0, "unit": "gram" },
          { "name": "Sambar ", "calories": 0.6, "unit": "gram" },
          { "name": "Coconut Chutney ", "calories": 40, "unit": "tbsp" },
          { "name": "Tomato Chutney ", "calories": 25, "unit": "tbsp" },
          { "name": "Mint Chutney ", "calories": 20, "unit": "tbsp" },
          { "name": "Potato Masala ", "calories": 0.9, "unit": "gram" },
          { "name": "Chana Curry ", "calories": 0.9, "unit": "gram" },
          { "name": "Mulaku Chammanthi ", "calories": 25, "unit": "tbsp" },
          { "name": "Kappa Puzhukku ", "calories": 0.8, "unit": "gram" },
          { "name": "Thari Kanji ", "calories": 0.5, "unit": "gram" },
          { "name": "Vendakka Stew ", "calories": 0.6, "unit": "gram" },
          { "name": "Kumbalanga Stew ", "calories": 0.6, "unit": "gram" },
          { "name": "Kappa Vevichathu ", "calories": 0.7, "unit": "gram" },
          { "name": "Red Chilli Chutney ", "calories": 30, "unit": "tbsp" },
          { "name": "Pazham Kanji ", "calories": 0.5, "unit": "gram" },
          { "name": "Uluva Kanji ", "calories": 0.5, "unit": "gram" },
          { "name": "Vegetable Kurma ", "calories": 0.7, "unit": "gram" },
          { "name": "Avial ", "calories": 0.7, "unit": "gram" }
        ]
      }
    },
    "lunch": {
      "base_items": {
        "veg": {
          "core_items": [
            { "name": "Rice", "calories": 180, "unit": "cup" },
            { "name": "Brown Rice", "calories": 215, "unit": "cup" },
            { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
            { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
            { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
            { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
            { "name": "Kaima Rice", "calories": 185, "unit": "cup" },
            { "name": "Neychoru", "calories": 280, "unit": "cup" },
            { "name": "Tomato Rice", "calories": 220, "unit": "cup" },
            { "name": "Lemon Rice", "calories": 240, "unit": "cup" },
            { "name": "Curd Rice", "calories": 200, "unit": "cup" },
            { "name": "Tamarind Rice", "calories": 250, "unit": "cup" },
            { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Kerala Sadya", "calories": 400, "unit": "plate" },
            { "name": "Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Pulao", "calories": 250, "unit": "cup" },
            { "name": "Vegetable Biryani", "calories": 255, "unit": "cup" },
            { "name": "Thalassery Veg Biryani", "calories": 260, "unit": "cup" }
          ]
        },
        "non_veg": {
          "core_items": [
            { "name": "Rice", "calories": 180, "unit": "cup" },
            { "name": "Brown Rice", "calories": 215, "unit": "cup" },
            { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
            { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
            { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
            { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
            { "name": "Kaima Rice", "calories": 185, "unit": "cup" },
            { "name": "Neychoru", "calories": 280, "unit": "cup" },
            { "name": "Tomato Rice", "calories": 220, "unit": "cup" },
            { "name": "Lemon Rice", "calories": 240, "unit": "cup" },
            { "name": "Curd Rice", "calories": 200, "unit": "cup" },
            { "name": "Tamarind Rice", "calories": 250, "unit": "cup" },
            { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Kerala Sadya", "calories": 400, "unit": "plate" },
            { "name": "Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Pulao", "calories": 250, "unit": "cup" },
            { "name": "Biryani", "calories": 325, "unit": "cup" },
            { "name": "Vegetable Biryani", "calories": 255, "unit": "cup" },
            { "name": "Thalassery Veg Biryani", "calories": 260, "unit": "cup" }
          ]
        },
        "vegan": {
          "core_items": [
            { "name": "Rice ", "calories": 175, "unit": "cup" },
            { "name": "Brown Rice ", "calories": 210, "unit": "cup" },
            { "name": "Steamed Rice ", "calories": 175, "unit": "cup" },
            { "name": "Basmati Rice ", "calories": 185, "unit": "cup" },
            { "name": "Jeera Rice ", "calories": 195, "unit": "cup" },
            { "name": "Kaima Rice ", "calories": 180, "unit": "cup" },
            { "name": "Tomato Rice ", "calories": 215, "unit": "cup" },
            { "name": "Lemon Rice ", "calories": 235, "unit": "cup" },
            { "name": "Tamarind Rice ", "calories": 245, "unit": "cup" },
            { "name": "Coconut Milk Rice ", "calories": 265, "unit": "cup" },
            { "name": "Chapati ", "calories": 105, "unit": "piece" },
            { "name": "Roti ", "calories": 105, "unit": "piece" },
            { "name": "Parotta ", "calories": 270, "unit": "piece" },
            { "name": "Pathiri ", "calories": 115, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Kerala Sadya ", "calories": 395, "unit": "plate" },
            { "name": "Fried Rice ", "calories": 275, "unit": "cup" },
            { "name": "Pulao ", "calories": 245, "unit": "cup" },
            { "name": "Vegetable Biryani ", "calories": 250, "unit": "cup" },
            { "name": "Thalassery Veg Biryani ", "calories": 255, "unit": "cup" }
          ]
        }
      },
      "veg_items": {
        "gravy": [
          { "name": "Sambar", "calories": 0.6, "unit": "gram" },
          { "name": "Rasam", "calories": 0.3, "unit": "gram" },
          { "name": "Moru Curry", "calories": 0.5, "unit": "gram" },
          { "name": "Avial", "calories": 0.8, "unit": "gram" },
          { "name": "Olan", "calories": 0.4, "unit": "gram" },
          { "name": "Kalan", "calories": 0.6, "unit": "gram" },
          { "name": "Erissery", "calories": 0.7, "unit": "gram" },
          { "name": "Pachadi", "calories": 0.6, "unit": "gram" },
          { "name": "Inji Curry", "calories": 0.4, "unit": "gram" },
          { "name": "Theeyal", "calories": 0.7, "unit": "gram" },
          { "name": "Koottu Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Pulissery", "calories": 0.6, "unit": "gram" },
          { "name": "Parippu Curry", "calories": 0.7, "unit": "gram" },
          { "name": "Coconut Chammanthi", "calories": 40, "unit": "tbsp" },
          { "name": "Bitter Gourd Theeyal", "calories": 0.7, "unit": "gram" },
          { "name": "Ash Gourd Pulissery", "calories": 0.5, "unit": "gram" },
          { "name": "Beetroot Pachadi", "calories": 0.6, "unit": "gram" },
          { "name": "Okra Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Tomato Rasam", "calories": 0.3, "unit": "gram" },
          { "name": "Ulli Theeyal", "calories": 0.7, "unit": "gram" },
          { "name": "Drumstick Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Jackfruit Erissery", "calories": 0.7, "unit": "gram" },
          { "name": "Pumpkin Curry", "calories": 0.5, "unit": "gram" },
          { "name": "Mango Pulissery", "calories": 0.6, "unit": "gram" },
          { "name": "Vegetable Roast", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Ishtu", "calories": 0.7, "unit": "gram" },
          { "name": "Raw Mango Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Dal Fry", "calories": 0.8, "unit": "gram" },
          { "name": "Vegetable Kurma", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Stew", "calories": 0.7, "unit": "gram" },
          { "name": "Kadala Curry", "calories": 1.0, "unit": "gram" }
        ],
        "dry": [
          { "name": "Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Long Beans Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Cabbage Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Chena Mezhukkupuratti", "calories": 1.0, "unit": "gram" },
          { "name": "Kovakka Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Payar Mezhukkupuratti", "calories": 0.7, "unit": "gram" },
          { "name": "Koorka Fry", "calories": 0.9, "unit": "gram" },
          { "name": "Kaya Mezhukkupuratti", "calories": 1.0, "unit": "gram" },
          { "name": "Veg Manchurian", "calories": 1.1, "unit": "gram" },
          { "name": "Banana Chips", "calories": 150, "unit": "serving" },
          { "name": "Sharkkara Upperi", "calories": 180, "unit": "serving" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Kerala Fish Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Meen Vevichathu", "calories": 1.2, "unit": "gram" },
          { "name": "Sardine Curry", "calories": 1.1, "unit": "gram" },
          { "name": "Ayala Curry", "calories": 1.1, "unit": "gram" },
          { "name": "Prawns Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Chicken Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Nadan Kozhi Curry", "calories": 1.3, "unit": "gram" },
          { "name": "Chicken Chettinad", "calories": 1.3, "unit": "gram" },
          { "name": "Mutton Curry", "calories": 1.4, "unit": "gram" },
          { "name": "Mutton Stew", "calories": 1.3, "unit": "gram" },
          { "name": "Duck Curry", "calories": 1.3, "unit": "gram" },
          { "name": "Egg Curry", "calories": 0.9, "unit": "gram" },
          { "name": "Fish Molee", "calories": 1.1, "unit": "gram" }
        ],
        "dry": [
          { "name": "Meen Pollichathu", "calories": 1.6, "unit": "gram" },
          { "name": "Fish Fry", "calories": 175, "unit": "piece" },
          { "name": "King Fish Fry", "calories": 200, "unit": "piece" },
          { "name": "Crab Roast", "calories": 1.7, "unit": "gram" },
          { "name": "Prawns Roast", "calories": 1.6, "unit": "gram" },
          { "name": "Prawns Masala", "calories": 1.6, "unit": "gram" },
          { "name": "Kanava Roast", "calories": 1.6, "unit": "gram" },
          { "name": "Kanava Thoran", "calories": 1.1, "unit": "gram" },
          { "name": "Mussel Fry", "calories": 1.1, "unit": "gram" },
          { "name": "Chicken Roast", "calories": 1.9, "unit": "gram" },
          { "name": "Chicken Varattiyathu", "calories": 1.8, "unit": "gram" },
          { "name": "Pepper Chicken Roast", "calories": 1.8, "unit": "gram" },
          { "name": "Chicken Fry", "calories": 1.9, "unit": "gram" },
          { "name": "Mutton Varattiyathu", "calories": 1.9, "unit": "gram" },
          { "name": "Beef Ularthiyathu", "calories": 1.9, "unit": "gram" },
          { "name": "Beef Roast", "calories": 2.0, "unit": "gram" },
          { "name": "Beef Fry", "calories": 2.1, "unit": "gram" },
          { "name": "Duck Roast", "calories": 1.8, "unit": "gram" },
          { "name": "Egg Roast", "calories": 1.2, "unit": "gram" },
          { "name": "Mutta Thoran", "calories": 1.0, "unit": "gram" },
          { "name": "Thalassery Chicken Biryani", "calories": 1.6, "unit": "gram" },
          { "name": "Malabar Mutton Biryani", "calories": 1.7, "unit": "gram" },
          { "name": "Fish Biryani", "calories": 1.5, "unit": "gram" },
          { "name": "Prawns Biryani", "calories": 1.6, "unit": "gram" },
          { "name": "Egg Biryani", "calories": 1.4, "unit": "gram" },
          { "name": "Chicken Manchurian", "calories": 1.2, "unit": "gram" },
          { "name": "Mutton Fry", "calories": 1.9, "unit": "gram" }
        ]
      },
      "vegan_items": {
        "dry": [
          { "name": "Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Long Beans Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Cabbage Thoran ", "calories": 0.5, "unit": "gram" },
          { "name": "Chena Mezhukkupuratti ", "calories": 1.0, "unit": "gram" },
          { "name": "Kovakka Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Payar Mezhukkupuratti ", "calories": 0.7, "unit": "gram" },
          { "name": "Koorka Fry ", "calories": 0.8, "unit": "gram" },
          { "name": "Kaya Mezhukkupuratti ", "calories": 1.0, "unit": "gram" },
          { "name": "Veg Manchurian ", "calories": 1.1, "unit": "gram" },
          { "name": "Banana Chips ", "calories": 145, "unit": "serving" },
          { "name": "Sharkkara Upperi ", "calories": 175, "unit": "serving" }
        ],
        "gravy": [
          { "name": "Sambar ", "calories": 0.6, "unit": "gram" },
          { "name": "Rasam ", "calories": 0.3, "unit": "gram" },
          { "name": "Moru Curry ", "calories": 0.5, "unit": "gram" },
          { "name": "Avial ", "calories": 0.7, "unit": "gram" },
          { "name": "Olan ", "calories": 0.4, "unit": "gram" },
          { "name": "Kalan ", "calories": 0.6, "unit": "gram" },
          { "name": "Erissery ", "calories": 0.6, "unit": "gram" },
          { "name": "Pachadi ", "calories": 0.6, "unit": "gram" },
          { "name": "Inji Curry ", "calories": 0.3, "unit": "gram" },
          { "name": "Theeyal ", "calories": 0.7, "unit": "gram" },
          { "name": "Koottu Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Pulissery ", "calories": 0.5, "unit": "gram" },
          { "name": "Parippu Curry ", "calories": 0.7, "unit": "gram" },
          { "name": "Coconut Chammanthi ", "calories": 35, "unit": "tbsp" },
          { "name": "Bitter Gourd Theeyal ", "calories": 0.7, "unit": "gram" },
          { "name": "Ash Gourd Pulissery ", "calories": 0.5, "unit": "gram" },
          { "name": "Beetroot Pachadi ", "calories": 0.6, "unit": "gram" },
          { "name": "Okra Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Tomato Rasam ", "calories": 0.3, "unit": "gram" },
          { "name": "Ulli Theeyal ", "calories": 0.7, "unit": "gram" },
          { "name": "Drumstick Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Jackfruit Erissery ", "calories": 0.7, "unit": "gram" },
          { "name": "Pumpkin Curry ", "calories": 0.5, "unit": "gram" },
          { "name": "Mango Pulissery ", "calories": 0.6, "unit": "gram" },
          { "name": "Vegetable Roast ", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Ishtu ", "calories": 0.7, "unit": "gram" },
          { "name": "Raw Mango Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Dal Fry ", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Kurma ", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Stew ", "calories": 0.6, "unit": "gram" },
          { "name": "Kadala Curry ", "calories": 1.0, "unit": "gram" }
        ]
      }
    },
    "dinner": {
      "base_items": {
        "veg": {
          "core_items": [
            { "name": "Rice", "calories": 180, "unit": "cup" },
            { "name": "Brown Rice", "calories": 215, "unit": "cup" },
            { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
            { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
            { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
            { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
            { "name": "Neychoru", "calories": 280, "unit": "cup" },
            { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Kerala Parotta", "calories": 280, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Pulao", "calories": 250, "unit": "cup" },
            { "name": "Kothu Parotta", "calories": 350, "unit": "cup" },
            { "name": "Vegetable Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Corn & Peas Pulao", "calories": 260, "unit": "cup" },
            { "name": "Ela Ada (Light dinner)", "calories": 150, "unit": "piece" }
          ]
        },
        "non_veg": {
          "core_items": [
            { "name": "Rice", "calories": 180, "unit": "cup" },
            { "name": "Brown Rice", "calories": 215, "unit": "cup" },
            { "name": "Steamed Rice", "calories": 180, "unit": "cup" },
            { "name": "Basmati Rice", "calories": 190, "unit": "cup" },
            { "name": "Jeera Rice", "calories": 200, "unit": "cup" },
            { "name": "Ghee Rice", "calories": 265, "unit": "cup" },
            { "name": "Neychoru", "calories": 280, "unit": "cup" },
            { "name": "Coconut Milk Rice", "calories": 270, "unit": "cup" },
            { "name": "Chapati", "calories": 110, "unit": "piece" },
            { "name": "Roti", "calories": 110, "unit": "piece" },
            { "name": "Parotta", "calories": 275, "unit": "piece" },
            { "name": "Kerala Parotta", "calories": 280, "unit": "piece" },
            { "name": "Pathiri", "calories": 120, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Pulao", "calories": 250, "unit": "cup" },
            { "name": "Biryani", "calories": 325, "unit": "cup" },
            { "name": "Kothu Parotta", "calories": 350, "unit": "cup" },
            { "name": "Vegetable Fried Rice", "calories": 280, "unit": "cup" },
            { "name": "Corn & Peas Pulao", "calories": 260, "unit": "cup" },
            { "name": "Ela Ada (Light dinner)", "calories": 150, "unit": "piece" }
          ]
        },
        "vegan": {
          "core_items": [
            { "name": "Rice ", "calories": 175, "unit": "cup" },
            { "name": "Brown Rice ", "calories": 210, "unit": "cup" },
            { "name": "Steamed Rice ", "calories": 175, "unit": "cup" },
            { "name": "Basmati Rice ", "calories": 185, "unit": "cup" },
            { "name": "Jeera Rice ", "calories": 195, "unit": "cup" },
            { "name": "Neychoru ", "calories": 275, "unit": "cup" },
            { "name": "Coconut Milk Rice ", "calories": 265, "unit": "cup" },
            { "name": "Chapati ", "calories": 105, "unit": "piece" },
            { "name": "Roti ", "calories": 105, "unit": "piece" },
            { "name": "Parotta ", "calories": 270, "unit": "piece" },
            { "name": "Kerala Parotta ", "calories": 275, "unit": "piece" },
            { "name": "Pathiri ", "calories": 115, "unit": "piece" }
          ],
          "complete_dishes": [
            { "name": "Fried Rice ", "calories": 275, "unit": "cup" },
            { "name": "Pulao ", "calories": 245, "unit": "cup" },
            { "name": "Kothu Parotta ", "calories": 345, "unit": "cup" },
            { "name": "Vegetable Fried Rice ", "calories": 275, "unit": "cup" },
            { "name": "Corn & Peas Pulao ", "calories": 255, "unit": "cup" },
            { "name": "Ela Ada (Light dinner, Vegan)", "calories": 145, "unit": "piece" }
          ]
        }
      },
      "veg_items": {
        "gravy": [
          { "name": "Vegetable Kurma", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Stew", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Ishtu", "calories": 0.7, "unit": "gram" },
          { "name": "Chakka Puzhukku", "calories": 0.6, "unit": "gram" },
          { "name": "Kadala Curry", "calories": 1.0, "unit": "gram" },
          { "name": "Tomato Kurma", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Masala", "calories": 0.8, "unit": "gram" },
          { "name": "Potato Curry", "calories": 0.9, "unit": "gram" },
          { "name": "Dal Fry", "calories": 0.8, "unit": "gram" },
          { "name": "Paneer Masala", "calories": 1.2, "unit": "gram" },
          { "name": "Pumpkin Curry", "calories": 0.5, "unit": "gram" },
          { "name": "Beetroot Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Cucumber Pachadi", "calories": 0.5, "unit": "gram" },
          { "name": "Mango Curry", "calories": 0.6, "unit": "gram" },
          { "name": "Mushroom Curry", "calories": 0.7, "unit": "gram" },
          { "name": "Paneer Butter Masala", "calories": 1.4, "unit": "gram" },
          { "name": "Baby Corn Kurma", "calories": 0.7, "unit": "gram" },
          { "name": "Soya Chunk Curry", "calories": 0.8, "unit": "gram" },
          { "name": "Pineapple Pulissery", "calories": 0.6, "unit": "gram" },
          { "name": "Chena Theeyal", "calories": 0.7, "unit": "gram" },
          { "name": "Nenthra Pazham Curry", "calories": 0.7, "unit": "gram" },
          { "name": "Vendakka Masala", "calories": 0.6, "unit": "gram" },
          { "name": "Chammanthi", "calories": 40, "unit": "tbsp" },
          { "name": "Chutney", "calories": 35, "unit": "tbsp" },
          { "name": "Mint Chutney", "calories": 25, "unit": "tbsp" }
        ],
        "dry": [
          { "name": "Vegetable Cutlet", "calories": 150, "unit": "piece" },
          { "name": "Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Bitter Gourd Fry", "calories": 0.8, "unit": "gram" },
          { "name": "Cabbage Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Beans Mezhukkupuratti", "calories": 0.7, "unit": "gram" },
          { "name": "Drumstick Leaves Thoran", "calories": 0.6, "unit": "gram" },
          { "name": "Carrot Thoran", "calories": 0.5, "unit": "gram" },
          { "name": "Raw Banana Fry", "calories": 0.9, "unit": "gram" },
          { "name": "Veg Roll", "calories": 200, "unit": "piece" },
          { "name": "Mushroom Thoran", "calories": 0.7, "unit": "gram" },
          { "name": "Soya Thoran", "calories": 0.7, "unit": "gram" }
        ]
      },
      "non_veg_items": {
        "gravy": [
          { "name": "Chicken Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Beef Curry", "calories": 1.5, "unit": "gram" },
          { "name": "Beef Stew", "calories": 1.4, "unit": "gram" },
          { "name": "Mutton Curry", "calories": 1.4, "unit": "gram" },
          { "name": "Mutton Stew", "calories": 1.3, "unit": "gram" },
          { "name": "Fish Molee", "calories": 1.1, "unit": "gram" },
          { "name": "Meen Vevichathu", "calories": 1.2, "unit": "gram" },
          { "name": "Fish Molly", "calories": 1.1, "unit": "gram" },
          { "name": "Kanava Curry", "calories": 1.2, "unit": "gram" },
          { "name": "Egg Curry", "calories": 0.9, "unit": "gram" },
          { "name": "Egg Kurma", "calories": 0.9, "unit": "gram" },
          { "name": "Duck Curry", "calories": 1.3, "unit": "gram" }
        ],
        "dry": [
          { "name": "Chicken Roast", "calories": 1.9, "unit": "gram" },
          { "name": "Chicken Fried Rice", "calories": 1.4, "unit": "gram" },
          { "name": "Chicken 65", "calories": 1.3, "unit": "gram" },
          { "name": "Chicken Chukka", "calories": 1.4, "unit": "gram" },
          { "name": "Chicken Kothu", "calories": 1.6, "unit": "gram" },
          { "name": "Beef Fry", "calories": 2.1, "unit": "gram" },
          { "name": "Beef Roast", "calories": 2.0, "unit": "gram" },
          { "name": "Beef Kothu", "calories": 1.7, "unit": "gram" },
          { "name": "Mutton Fry", "calories": 1.9, "unit": "gram" },
          { "name": "Mutton Ularthiyathu", "calories": 1.9, "unit": "gram" },
          { "name": "Mutton Kothu", "calories": 1.6, "unit": "gram" },
          { "name": "Fish Fry", "calories": 175, "unit": "piece" },
          { "name": "Squid Roast", "calories": 1.3, "unit": "gram" },
          { "name": "Mussel Fry", "calories": 1.1, "unit": "gram" },
          { "name": "Egg Roast", "calories": 0.9, "unit": "gram" },
          { "name": "Egg Masala", "calories": 0.9, "unit": "gram" },
          { "name": "Egg Fried Rice", "calories": 1.3, "unit": "gram" },
          { "name": "Egg Kothu", "calories": 1.2, "unit": "gram" },
          { "name": "Prawns Fried Rice", "calories": 1.5, "unit": "gram" },
          { "name": "Prawns Masala Wrap", "calories": 290, "unit": "piece" },
          { "name": "Chicken Wrap", "calories": 310, "unit": "piece" },
          { "name": "Fish Wrap", "calories": 270, "unit": "piece" },
          { "name": "Egg Wrap", "calories": 220, "unit": "piece" },
          { "name": "Duck Roast", "calories": 1.4, "unit": "gram" }
        ]
      },
      "vegan_items": {
        "dry": [
          { "name": "Vegetable Cutlet ", "calories": 145, "unit": "piece" },
          { "name": "Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Bitter Gourd Fry ", "calories": 0.8, "unit": "gram" },
          { "name": "Cabbage Thoran ", "calories": 0.5, "unit": "gram" },
          { "name": "Beans Mezhukkupuratti ", "calories": 0.7, "unit": "gram" },
          { "name": "Drumstick Leaves Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Carrot Thoran ", "calories": 0.5, "unit": "gram" },
          { "name": "Raw Banana Fry ", "calories": 0.9, "unit": "gram" },
          { "name": "Veg Roll ", "calories": 195, "unit": "piece" },
          { "name": "Mushroom Thoran ", "calories": 0.6, "unit": "gram" },
          { "name": "Soya Thoran ", "calories": 0.7, "unit": "gram" }
        ],
        "gravy": [
          { "name": "Vegetable Kurma ", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Stew ", "calories": 0.6, "unit": "gram" },
          { "name": "Vegetable Ishtu ", "calories": 0.7, "unit": "gram" },
          { "name": "Chakka Puzhukku ", "calories": 0.6, "unit": "gram" },
          { "name": "Kadala Curry ", "calories": 1.0, "unit": "gram" },
          { "name": "Tomato Kurma ", "calories": 0.7, "unit": "gram" },
          { "name": "Vegetable Masala ", "calories": 0.7, "unit": "gram" },
          { "name": "Potato Curry ", "calories": 0.9, "unit": "gram" },
          { "name": "Dal Fry ", "calories": 0.7, "unit": "gram" },
          { "name": "Pumpkin Curry ", "calories": 0.5, "unit": "gram" },
          { "name": "Beetroot Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Cucumber Pachadi ", "calories": 0.5, "unit": "gram" },
          { "name": "Mango Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Mushroom Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Baby Corn Kurma ", "calories": 0.7, "unit": "gram" },
          { "name": "Soya Chunk Curry ", "calories": 0.8, "unit": "gram" },
          { "name": "Pineapple Pulissery ", "calories": 0.6, "unit": "gram" },
          { "name": "Chena Theeyal ", "calories": 0.7, "unit": "gram" },
          { "name": "Nenthra Pazham Curry ", "calories": 0.6, "unit": "gram" },
          { "name": "Vendakka Masala ", "calories": 0.6, "unit": "gram" },
          { "name": "Chammanthi ", "calories": 35, "unit": "tbsp" },
          { "name": "Chutney ", "calories": 30, "unit": "tbsp" },
          { "name": "Mint Chutney ", "calories": 20, "unit": "tbsp" }
        ]
      }
    }
  }